### PR TITLE
Break changelog page into one page per release

### PR DESCRIPTION
**Pull request by StachuDotNet**
Changelog:
```
Documentation
- splits the "Changelog" page into separate pages per monthly Release
  breaks old links that reference Releases by URL fragment (e.g. `...changelog#release-7`)
```

This PR:
- moves the 'root' `changelog.md` page from `/references` to `/`; updates sidebar link and the docusaurus redirect
- extracts out 8 posts for Releases 1-8 e.g. `/changelog/release-8`.
  for most of them, this included decreasing `h2`s to `h1`s, `h3`s to `h2`s, etc.
- create a new root `changelog` page that's a directory for the individual pages

Peek 2022-12-12 15-29

Things that aren't great:
- the "Release 1" is still huge. We could break this down into multiple pages, but I sort of think it's OK like this since it's old.

- the individual Release pages don't have a link to the root "Changelog" directory

  we could get this done really easily if we added a link to all individual release pages from the sidebar. The breadcrumbs would auto-generate such a link. That said, once we get to a ~dozen releases, it might start to look ridiculous with many links. We could also add links directly to each .md page somewhere

- old URLs referencing a specific section of the big ol' changelog page will now just go to the directory page

  docusaurus' `plugin-client-redirects` does not support URL fragments. [this](https://github.com/mkdocs/mkdocs-redirects/issues/16#issuecomment-810276400) comment mentions an option of how we might support redirects to the appropriate page with another tool

### CODE REVIEW

**Comment by pbiggar** [comment]
> * How does this look to you overall? Is it what you expected?

Yeah, this looks good. I figured we'd have a sidebar entry for changelog with a list of all the changelogs under it.

> * Do you think the date display is OK?

It's kinda weird, I'd expect "October 1, 2022". Why'd you go with this option?

> * Does it bother you that the "release 1" page is long?

No.

> * Is there a better name for "Release 1"?

If we come up with a new name then we'll have to explain why there's no "Release 1" so this seems fine.

> * Do you think we should move the "Changelog" link to the root level of the sidebar?

yes!

> * Is it worth exploring more to see if the given [this](https://github.com/mkdocs/mkdocs-redirects/issues/16#issuecomment-810276400) path will allow us to redirect # URLs? Or maybe it's not worth it.

Probably not worth it.

> * It annoys me that I can't get to the root 'changelog' page from an individual release's page. Any opinions on what to do about this?

I suspect if the root changelog was a "section" this might help. I think the odd structure might be causing this.

**Review by pbiggar — APPROVED** [review]
Fine to merge as is and do the rest as a followup if you prefer.

**Comment by StachuDotNet** [comment]
> > * Do you think the date display is OK?
> 
> It's kinda weird, I'd expect "October 1, 2022". Why'd you go with this option?

I was referring to the font size of the dates on individual release pages, actually.
That said, yeah the formatting of the dates is weird on the index page for no good reason, fixing that.

**Comment by StachuDotNet** [comment]
image
This looks bad with "Darklang Release X" repeated.

I updated the sidebar to instead look like "Release N - [Date]". 
image

What do you think?

**Comment by pbiggar** [comment]
> > > * Do you think the date display is OK?

> I was referring to the font size of the dates on individual release pages, actually.

Oh yeah, not great. Maybe italics? They could also go in the title (we can specify slugs so they wouldn't have to go in there)

**Pull request merged**
