### PR TITLE
Add yet another missing word

### PR DESCRIPTION
**Pull request by aalaap**
This time it's "or *an* entirely separate project".

### CODE REVIEW

**Comment by pbiggar** [comment]
This one is as intended. Is it unclear?

**Comment by aalaap** [comment]
@pbiggar It just seems grammatically incorrect - there's gotta be an *a*, *an*, *the*, or something like that, don't you think? Perhaps we can get a few others to chime in on this one if you're not sure.

**Comment by pbiggar** [comment]
It's an extension of "per company", so you'd say "per entirely separate project".

**Comment by aalaap** [comment]
I see what you're saying, but it doesn't seem to read too well. Maybe "per company or project" would make sense, but that "entirely separate" seems to make it confusing. I'm not sure if its necessary, since a project, I feel, implies that it would be separate, and in it's entirety...

**Comment by pbiggar** [comment]
Yeah, I agree. The implication we were going for is that we want people to use just one canvas, but of course, we don't have the features to make that really viable yet. So maybe removing the sentence entirely would be the right solution.

**Comment by aalaap** [comment]
No, no. I think it's an important point that shouldn't be removed - it really fuels the kind of thinking that would be required to go into architecting Dark apps. It just needs to be simplified.

**Pull request closed without merging**
