### PR TITLE
add contextualSearch option to algolia field, set to false

### PR DESCRIPTION
**Pull request by kate-grant**
Added contextualSearch option set to "false". W/O option specified, contextualSearch defaults to "true", which searches w/ facetFilters.

### CODE REVIEW

**Comment by pbiggar** [comment]
Great, thank you! Does search work locally with this, or are we waiting to see in production?

**Comment by kate-grant** [comment]
The search works locally search bar > popup results. Even w/o the facetFilters, results seem relevant and top results are well-targeted for search relevancy. A remaining issue is when clicking on the "see all results" option at the bottom of the search popup, this seems to re-query w/ the facetFilters. Should I look into that as a new PR?

**Comment by pbiggar** [comment]
> A remaining issue is when clicking on the "see all results" option at the bottom of the search popup, this seems to re-query w/ the facetFilters. Should I look into that as a new PR?

I'm not sure what that means, can you describe the difference?

**Comment by kate-grant** [comment]
The initial search popup from the navbar search only displays so many results before displaying a "see all results" link--this link is not working correctly, so remaining results cannot be viewed. The url at "see all results", https://docs.darklang.com/search?q=____, displays "no results were found" when the link is clicked (and also when trying any search directly on this search page). Following the link is triggering a completely new algolia search using the facetFilters (they show up in the payload form data for the query that happens when clicking on the link, despite the contextualSearch option change). [Example](https://docs.darklang.com/search?q=hello)

**Pull request merged**
